on:
    workflow_call:
        inputs:
            isBackend:
                required: true
                type: boolean

jobs:
    backend:
        if: ${{ inputs.isBackend }}
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        steps:
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22.22.3'
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Install Dependencies
              uses: pnpm/action-setup@v4
              with:
                  run_install: |
                      args: [--frozen-lockfile, --strict-peer-dependencies]
                      cwd: ./backend
            - name: Build
              run: pnpm build
            - name: Lint
              run: pnpm lint
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 21
            - name: Cache Firebase Emulators
              uses: actions/cache@v4
              with:
                  path: ~/.cache/firebase/emulators
                  key: firebase-emulators-${{ runner.os }}
            - name: Test
              run: pnpm test:emulator
