name: Changes Workflow

on:
    workflow_call:
        outputs:
            backend:
                value: ${{ jobs.changes.outputs.backend }}
            frontend:
                value: ${{ jobs.changes.outputs.frontend }}
            shared:
                value: ${{ jobs.changes.outputs.shared }}

jobs:
    changes:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./
        # Required permissions
        permissions:
            pull-requests: read
        # Set job outputs to values from filter step
        outputs:
            backend: ${{ steps.filter.outputs.backend }}
            frontend: ${{ steps.filter.outputs.frontend }}
            shared: ${{ steps.filter.outputs.shared }}
        steps:
            - uses: actions/checkout@master
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  filters: |
                      backend:
                        - 'backend/**'
                        - 'shared/**'
                        - '.github/**'
                      frontend:
                        - 'frontend/**'
                        - 'shared/**'
                        - '.github/**'
                      shared:
                        - 'shared/**'
                        - '.github/**'
