name: Frontend

on:
    push:
        branches:
            - main

jobs:
    changes:
        uses: ./.github/workflows/changes.yml

    shared:
        needs: changes
        uses: ./.github/workflows/shared.yml
        with:
            isShared: ${{ needs.changes.outputs.shared == 'true' }}

    frontend:
        needs: changes
        uses: ./.github/workflows/frontend.yml
        with:
            isFrontend: ${{ needs.changes.outputs.frontend == 'true' }}

    backend:
        needs: changes
        uses: ./.github/workflows/backend.yml
        with:
            isBackend: ${{ needs.changes.outputs.backend == 'true' }}

    deploy:
        name: Deploy
        needs: [changes, backend]
        if: always() && !failure() && !cancelled() && ${{ needs.changes.outputs.backend == 'true' }}

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node
              uses: actions/setup-node@master
              with:
                  node-version: '24'
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Install Dependencies
              uses: pnpm/action-setup@v4
              with:
                  run_install: |
                      args: [--frozen-lockfile, --strict-peer-dependencies]
                      cwd: ./backend
            - name: Deploy functions to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only functions
              env:
                  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
                  PROJECT_ID: 'default'
                  PROJECT_PATH: '.'
