name: CI - Cloud

on:
    push:
        branches:
            - main
        paths:
            - 'backend/**'
            - 'shared/**'
            - '.github/**'

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Install Dependencies
              run: yarn ci
              working-directory: ./backend
            - name: Deploy functions to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only functions
              env:
                  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
                  PROJECT_ID: 'default'
                  PROJECT_PATH: '.'
